# Generated by Django 4.0.6 on 2022-07-09 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rooms_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='file',
        ),
        migrations.CreateModel(
            name='RoomsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rooms')),
            ],
        ),
    ]
