# Generated by Django 4.0.6 on 2022-07-09 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_room_roomsimages_rooms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AlterModelOptions(
            name='roomsimages',
            options={'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AlterField(
            model_name='rooms',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='headname',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='roomsimages',
            name='images',
            field=models.FileField(upload_to='images', verbose_name='картинка'),
        ),
        migrations.CreateModel(
            name='RoomsCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_el', models.CharField(max_length=200, verbose_name='Стоимость пункт')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rooms')),
            ],
            options={
                'verbose_name': 'Стоимость',
                'verbose_name_plural': 'Стоимость',
            },
        ),
    ]
