# Generated by Django 4.0.6 on 2022-07-09 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_rooms_options_alter_roomsimages_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomscost',
            name='cost_el',
            field=models.CharField(max_length=200, verbose_name='пункт'),
        ),
        migrations.CreateModel(
            name='RoomsDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_el', models.CharField(max_length=200, verbose_name='пункт')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rooms')),
            ],
            options={
                'verbose_name': 'Девайсы',
                'verbose_name_plural': 'Девайс',
            },
        ),
        migrations.CreateModel(
            name='RoomsAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_el', models.CharField(max_length=200, verbose_name='пункт')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rooms')),
            ],
            options={
                'verbose_name': 'Аксессуары',
                'verbose_name_plural': 'Аксессуар',
            },
        ),
    ]
