# Generated by Django 4.0.4 on 2022-07-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_site_options_siterules_sitecontacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitecontacts',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='siterules',
            options={'verbose_name': 'Правила', 'verbose_name_plural': 'Правила'},
        ),
    ]
