# Generated by Django 4.0.4 on 2022-07-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_cost_el_roomsaccessories_accessory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('number', models.CharField(max_length=100, verbose_name='номер телефона')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='номер телефона')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
            },
        ),
    ]
