# Generated by Django 4.0.6 on 2022-07-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
