# Generated by Django 4.0.4 on 2022-07-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_sitecontacts_options_alter_siterules_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomsaccessories',
            old_name='cost_el',
            new_name='accessory',
        ),
        migrations.RenameField(
            model_name='roomscost',
            old_name='cost_el',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='roomsdevices',
            old_name='cost_el',
            new_name='device',
        ),
    ]
