# Generated by Django 4.2.6 on 2023-10-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'заявку', 'verbose_name_plural': 'заявки'},
        ),
        migrations.AlterModelOptions(
            name='rooms',
            options={'verbose_name': 'Комнату', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': '', 'verbose_name_plural': 'Настройки сайта'},
        ),
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateTimeField(verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='sitecontacts',
            name='address',
            field=models.TextField(max_length=500, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='siterules',
            name='rule',
            field=models.TextField(max_length=1000, verbose_name='правило'),
        ),
    ]
